# Generated by Django 6.0.1 on 2026-02-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_readingsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='latest', max_length=20, unique=True)),
                ('results', models.JSONField(default=list)),
                ('city_alerts', models.JSONField(default=dict)),
                ('readings', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
