# Generated by Django 6.0.1 on 2026-02-04 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_suggestion_comment_suggestionvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['suggestion'], name='dashboard_c_suggest_24196e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='dashboard_c_created_582d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['-created_at'], name='dashboard_s_created_d402fa_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['author'], name='dashboard_s_author__b1e11a_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestionvote',
            index=models.Index(fields=['suggestion', 'value'], name='dashboard_s_suggest_4fb108_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestionvote',
            index=models.Index(fields=['user'], name='dashboard_s_user_id_924356_idx'),
        ),
    ]
