# Generated by Django 6.0.1 on 2026-02-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='hour_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='requests_this_hour',
            field=models.IntegerField(default=0),
        ),
    ]
